; Generated by c86 (BYU-NASM) 5.1 (beta) from yakc.i
	CPU	8086
	ALIGN	2
	jmp	main	; Jump to program start
	ALIGN	2
YKIdleCount:
	DW	0
running_flag:
	DW	0
ISRCallDepth:
	DW	0
lastRunTask:
	DW	0
YKCtxSwCount:
	DW	0
YKTickNum:
	DW	0
firstTime:
	DW	1
initContext:
	DW	0,0,0,0,0
	DW	0,0,0,0,0
	DW	0,0,512
	ALIGN	2
YKInitialize:
	; >>>>> Line:	33
	; >>>>> { 
	jmp	L_yakc_2
L_yakc_3:
	; >>>>> Line:	37
	; >>>>> YKNewTask(YKIdleTask, (void *) &IdleStk[256], 100); 
	mov	al, 100
	push	ax
	mov	ax, (L_yakc_1+512)
	push	ax
	mov	ax, YKIdleTask
	push	ax
	call	YKNewTask
	add	sp, 6
	; >>>>> Line:	39
	; >>>>> lastRunTask = YKRdyList; 
	mov	ax, word [YKRdyList]
	mov	word [lastRunTask], ax
	mov	sp, bp
	pop	bp
	ret
L_yakc_2:
	push	bp
	mov	bp, sp
	jmp	L_yakc_3
L_yakc_5:
	DB	"Entering idle task",0xA,0xD,0
	ALIGN	2
YKIdleTask:
	; >>>>> Line:	43
	; >>>>> { 
	jmp	L_yakc_6
L_yakc_7:
	; >>>>> Line:	44
	; >>>>> printString("Entering idle task\n\r"); 
	mov	ax, L_yakc_5
	push	ax
	call	printString
	add	sp, 2
	; >>>>> Line:	45
	; >>>>> while(1) 
	jmp	L_yakc_9
L_yakc_8:
	; >>>>> Line:	48
	; >>>>> tmp = YKIdleCount + 1; 
	mov	ax, word [YKIdleCount]
	inc	ax
	mov	word [bp-2], ax
	; >>>>> Line:	49
	; >>>>> YKIdleCount = tmp; 
	mov	ax, word [bp-2]
	mov	word [YKIdleCount], ax
L_yakc_9:
	jmp	L_yakc_8
L_yakc_10:
	mov	sp, bp
	pop	bp
	ret
L_yakc_6:
	push	bp
	mov	bp, sp
	push	cx
	jmp	L_yakc_7
	ALIGN	2
YKNewTask:
	; >>>>> Line:	59
	; >>>>> { 
	jmp	L_yakc_12
L_yakc_13:
	; >>>>> Line:	67
	; >>>>> newTCB = createTCB(taskStack, priority, initContext); 
	sub	sp, 26
	mov	di, sp
	mov	si, initContext
	mov	cx, 13
	rep
	movsw
	mov	al, byte [bp+8]
	xor	ah, ah
	push	ax
	push	word [bp+6]
	call	createTCB
	add	sp, 30
	mov	word [bp-2], ax
	; >>>>> Line:	69
	; >>>>> newTCB->context.sp = (int)(taskStack); 
	mov	si, word [bp-2]
	mov	ax, word [bp+6]
	mov	word [si], ax
	; >>>>> Line:	70
	; >>>>> newTCB->context.ip = (int)task; 
	mov	si, word [bp-2]
	add	si, 2
	mov	ax, word [bp+4]
	mov	word [si], ax
	; >>>>> Line:	71
	; >>>>> newTCB->context.bp = (int)taskStack; 
	mov	si, word [bp-2]
	add	si, 16
	mov	ax, word [bp+6]
	mov	word [si], ax
	; >>>>> Line:	72
	; >>>>> insertTCBIntoRdyList(newTCB); 
	push	word [bp-2]
	call	insertTCBIntoRdyList
	add	sp, 2
	; >>>>> Line:	76
	; >>>>> if (running_flag) 
	mov	ax, word [running_flag]
	test	ax, ax
	je	L_yakc_14
	; >>>>> Line:	78
	; >>>>> YKScheduler(); 
	call	YKScheduler
L_yakc_14:
	mov	sp, bp
	pop	bp
	ret
L_yakc_12:
	push	bp
	mov	bp, sp
	push	cx
	jmp	L_yakc_13
	ALIGN	2
YKRun:
	; >>>>> Line:	83
	; >>>>> { 
	jmp	L_yakc_16
L_yakc_17:
	; >>>>> Line:	86
	; >>>>> running_flag = 1; 
	mov	word [running_flag], 1
	; >>>>> Line:	89
	; >>>>> YKScheduler(); 
	call	YKScheduler
	mov	sp, bp
	pop	bp
	ret
L_yakc_16:
	push	bp
	mov	bp, sp
	jmp	L_yakc_17
	ALIGN	2
YKDelayTask:
	; >>>>> Line:	93
	; >>>>> { 
	jmp	L_yakc_19
L_yakc_20:
	; >>>>> Line:	98
	; >>>>> if (count == 0) 
	mov	ax, word [bp+4]
	test	ax, ax
	jne	L_yakc_21
	; >>>>> Line:	99
	; >>>>> return; 
	jmp	L_yakc_22
L_yakc_21:
	; >>>>> Line:	104
	; >>>>> YKRdyList->delay = count; 
	mov	si, word [YKRdyList]
	add	si, 30
	mov	ax, word [bp+4]
	mov	word [si], ax
	; >>>>> Line:	105
	; >>>>> YKEnterMutex(); 
	call	YKEnterMutex
	; >>>>> Line:	106
	; >>>>> != 0) 
	call	removeFirstTCBFromRdyList
	; >>>>> Line:	107
	; >>>>> YKExitMutex(); 
	call	YKExitMutex
	; >>>>> Line:	112
	; >>>>> YKScheduler(); 
	call	YKScheduler
L_yakc_22:
	mov	sp, bp
	pop	bp
	ret
L_yakc_19:
	push	bp
	mov	bp, sp
	jmp	L_yakc_20
	ALIGN	2
YKEnterISR:
	; >>>>> Line:	116
	; >>>>> { 
	jmp	L_yakc_24
L_yakc_25:
	; >>>>> Line:	117
	; >>>>> ISRCallDepth++; 
	inc	word [ISRCallDepth]
	mov	sp, bp
	pop	bp
	ret
L_yakc_24:
	push	bp
	mov	bp, sp
	jmp	L_yakc_25
	ALIGN	2
YKExitISR:
	; >>>>> Line:	121
	; >>>>> { 
	jmp	L_yakc_27
L_yakc_28:
	; >>>>> Line:	122
	; >>>>> ISRCallDepth--; 
	dec	word [ISRCallDepth]
	; >>>>> Line:	123
	; >>>>> if (ISRCallDepth == 0) 
	mov	ax, word [ISRCallDepth]
	test	ax, ax
	jne	L_yakc_29
	; >>>>> Line:	124
	; >>>>> YKScheduler(); 
	call	YKScheduler
L_yakc_29:
	mov	sp, bp
	pop	bp
	ret
L_yakc_27:
	push	bp
	mov	bp, sp
	jmp	L_yakc_28
	ALIGN	2
YKScheduler:
	; >>>>> Line:	128
	; >>>>> { 
	jmp	L_yakc_31
L_yakc_32:
	; >>>>> Line:	133
	; >>>>> if (firstTime) 
	mov	ax, word [firstTime]
	test	ax, ax
	je	L_yakc_33
	; >>>>> Line:	135
	; >>>>> firstTime = 0; 
	mov	word [firstTime], 0
	; >>>>> Line:	137
	; >>>>> YKCtxSwCount++; 
	inc	word [YKCtxSwCount]
	; >>>>> Line:	139
	; >>>>> YKFirstDispatcher(); 
	call	YKFirstDispatcher
	jmp	L_yakc_34
L_yakc_33:
	; >>>>> Line:	141
	; >>>>> else if (lastRunTask != YKRdyList) 
	mov	ax, word [YKRdyList]
	cmp	ax, word [lastRunTask]
	je	L_yakc_35
	; >>>>> Line:	144
	; >>>>> YKCtxSwCount++; 
	inc	word [YKCtxSwCount]
	; >>>>> Line:	146
	; >>>>> YKDispatcher(); 
	call	YKDispatcher
L_yakc_35:
L_yakc_34:
	mov	sp, bp
	pop	bp
	ret
L_yakc_31:
	push	bp
	mov	bp, sp
	jmp	L_yakc_32
L_yakc_37:
	DB	0xA,0
	ALIGN	2
YKTickHandler:
	; >>>>> Line:	152
	; >>>>> { 
	jmp	L_yakc_38
L_yakc_39:
	; >>>>> Line:	161
	; >>>>> tmp = YKSuspList; 
	mov	ax, word [YKSuspList]
	mov	word [bp-2], ax
	; >>>>> Line:	166
	; >>>>> printString("\n"); 
	mov	ax, L_yakc_37
	push	ax
	call	printString
	add	sp, 2
	; >>>>> Line:	168
	; >>>>> while(tmp != 0) 
	jmp	L_yakc_41
L_yakc_40:
	; >>>>> Line:	170
	; >>>>>  
	mov	si, word [bp-2]
	add	si, 30
	cmp	word [si], 0
	jle	L_yakc_43
	; >>>>> Line:	172
	; >>>>> (tmp->delay)--; 
	mov	si, word [bp-2]
	add	si, 30
	dec	word [si]
	; >>>>> Line:	173
	; >>>>> if (tmp->delay == 0) 
	mov	si, word [bp-2]
	add	si, 30
	mov	ax, word [si]
	test	ax, ax
	jne	L_yakc_44
	; >>>>> Line:	175
	; >>>>> tmp2 = tmp; 
	mov	ax, word [bp-2]
	mov	word [bp-4], ax
	; >>>>> Line:	176
	; >>>>> tmp = tmp->next; 
	mov	si, word [bp-2]
	add	si, 32
	mov	ax, word [si]
	mov	word [bp-2], ax
	; >>>>> Line:	178
	; >>>>> moveTCBToRdyList(tmp2); 
	push	word [bp-4]
	call	moveTCBToRdyList
	add	sp, 2
	jmp	L_yakc_45
L_yakc_44:
	; >>>>> Line:	181
	; >>>>> tmp = tmp->next; 
	mov	si, word [bp-2]
	add	si, 32
	mov	ax, word [si]
	mov	word [bp-2], ax
L_yakc_45:
	jmp	L_yakc_46
L_yakc_43:
	; >>>>> Line:	184
	; >>>>> tmp = tmp->next; 
	mov	si, word [bp-2]
	add	si, 32
	mov	ax, word [si]
	mov	word [bp-2], ax
L_yakc_46:
L_yakc_41:
	mov	ax, word [bp-2]
	test	ax, ax
	jne	L_yakc_40
L_yakc_42:
	; >>>>> Line:	186
	; >>>>> YKTickNum++; 
	inc	word [YKTickNum]
	; >>>>> Line:	189
	; >>>>> YKScheduler(); 
	call	YKScheduler
	mov	sp, bp
	pop	bp
	ret
L_yakc_38:
	push	bp
	mov	bp, sp
	sub	sp, 4
	jmp	L_yakc_39
	ALIGN	2
L_yakc_1:
	TIMES	512 db 0
