; Generated by c86 (BYU-NASM) 5.1 (beta) from lab4b_app.i
	CPU	8086
	ALIGN	2
	jmp	main	; Jump to program start
	ALIGN	2
ax:
	TIMES	2 db 0
bx:
	TIMES	2 db 0
cx:
	TIMES	2 db 0
dx:
	TIMES	2 db 0
si:
	TIMES	2 db 0
di:
	TIMES	2 db 0
bp:
	TIMES	2 db 0
es:
	TIMES	2 db 0
ds:
	TIMES	2 db 0
IF:
	TIMES	2 db 0
context:
	TIMES	2 db 0
IdleStk:
	TIMES	512 db 0
AStk:
	TIMES	512 db 0
BStk:
	TIMES	512 db 0
CStk:
	TIMES	512 db 0
