; Generated by c86 (BYU-NASM) 5.1 (beta) from interruptHandlers.i
	CPU	8086
	ALIGN	2
	jmp	main	; Jump to program start
	ALIGN	2
resetInterruptHandler:
	; >>>>> Line:	6
	; >>>>> { 
	jmp	L_interruptHandlers_1
L_interruptHandlers_2:
	; >>>>> Line:	7
	; >>>>> exit(0); 
	xor	al, al
	push	ax
	call	exit
	add	sp, 2
	mov	sp, bp
	pop	bp
	ret
L_interruptHandlers_1:
	push	bp
	mov	bp, sp
	jmp	L_interruptHandlers_2
	ALIGN	2
L_interruptHandlers_4:
	DW	0
L_interruptHandlers_5:
	DB	"TICK ",0
	ALIGN	2
tickInterruptHandler:
	; >>>>> Line:	11
	; >>>>> { 
	jmp	L_interruptHandlers_6
L_interruptHandlers_7:
	; >>>>> Line:	13
	; >>>>> tickCount++; 
	inc	word [L_interruptHandlers_4]
	; >>>>> Line:	14
	; >>>>> printNewLine(); 
	call	printNewLine
	; >>>>> Line:	15
	; >>>>> printString("TICK "); 
	mov	ax, L_interruptHandlers_5
	push	ax
	call	printString
	add	sp, 2
	; >>>>> Line:	16
	; >>>>> printInt(tickCount); 
	push	word [L_interruptHandlers_4]
	call	printInt
	add	sp, 2
	; >>>>> Line:	17
	; >>>>> printNewLine(); 
	call	printNewLine
	mov	sp, bp
	pop	bp
	ret
L_interruptHandlers_6:
	push	bp
	mov	bp, sp
	jmp	L_interruptHandlers_7
L_interruptHandlers_12:
	DB	") IGNORED",0
L_interruptHandlers_11:
	DB	"KEYPRESS (",0
L_interruptHandlers_10:
	DB	"DELAY COMPLETE",0
L_interruptHandlers_9:
	DB	"DELAY KEY PRESSED",0
	ALIGN	2
keyboardInterruptHandler:
	; >>>>> Line:	21
	; >>>>> { 
	jmp	L_interruptHandlers_13
L_interruptHandlers_14:
	; >>>>> Line:	23
	; >>>>> printNewLine(); 
	call	printNewLine
	; >>>>> Line:	24
	; >>>>> if (KeyBuffer == 'd') 
	cmp	word [KeyBuffer], 100
	jne	L_interruptHandlers_15
	; >>>>> Line:	26
	; >>>>> printString("DELAY KEY PRESSED"); 
	mov	ax, L_interruptHandlers_9
	push	ax
	call	printString
	add	sp, 2
	; >>>>> Line:	27
	; >>>>> count = 0; 
	mov	word [bp-2], 0
	; >>>>> Line:	28
	; >>>>> while (count < 5000) 
	jmp	L_interruptHandlers_17
L_interruptHandlers_16:
	; >>>>> Line:	30
	; >>>>> count++; 
	inc	word [bp-2]
L_interruptHandlers_17:
	cmp	word [bp-2], 5000
	jl	L_interruptHandlers_16
L_interruptHandlers_18:
	; >>>>> Line:	32
	; >>>>> printNewLine(); 
	call	printNewLine
	; >>>>> Line:	33
	; >>>>> printString("DELAY COMPLETE"); 
	mov	ax, L_interruptHandlers_10
	push	ax
	call	printString
	add	sp, 2
	; >>>>> Line:	34
	; >>>>> printNewLine(); 
	call	printNewLine
	jmp	L_interruptHandlers_19
L_interruptHandlers_15:
	; >>>>> Line:	38
	; >>>>> printString("KEYPRESS ("); 
	mov	ax, L_interruptHandlers_11
	push	ax
	call	printString
	add	sp, 2
	; >>>>> Line:	39
	; >>>>> printChar(KeyBuffer); 
	push	word [KeyBuffer]
	call	printChar
	add	sp, 2
	; >>>>> Line:	40
	; >>>>> printString(") IGNORED"); 
	mov	ax, L_interruptHandlers_12
	push	ax
	call	printString
	add	sp, 2
	; >>>>> Line:	41
	; >>>>> printNewLine(); 
	call	printNewLine
L_interruptHandlers_19:
	mov	sp, bp
	pop	bp
	ret
L_interruptHandlers_13:
	push	bp
	mov	bp, sp
	push	cx
	jmp	L_interruptHandlers_14
