; Generated by c86 (BYU-NASM) 5.1 (beta) from linkedList.i
	CPU	8086
	ALIGN	2
	jmp	main	; Jump to program start
	ALIGN	2
L_linkedList_3:
	DW	0
	ALIGN	2
createTCB:
	; >>>>> Line:	13
	; >>>>> { 
	jmp	L_linkedList_4
L_linkedList_5:
	; >>>>> Line:	14
	; >>>>> st = tcb; 
	mov	ax, word [L_linkedList_3]
	mov	cx, 36
	imul	cx
	add	ax, TCBarray
	mov	si, ax
	add	si, 24
	mov	ax, word [bp+4]
	mov	word [si], ax
	; >>>>> Line:	15
	; >>>>> TCBarray[currentListSize].priority = priority; 
	mov	ax, word [L_linkedList_3]
	mov	cx, 36
	imul	cx
	add	ax, TCBarray
	mov	si, ax
	add	si, 26
	mov	ax, word [bp+6]
	mov	word [si], ax
	; >>>>> Line:	16
	; >>>>> TCBarray[currentListSize].context = context; 
	lea	ax, [bp+8]
	mov	word [bp-2], ax
	mov	ax, word [L_linkedList_3]
	mov	cx, 36
	imul	cx
	add	ax, TCBarray
	mov	word [bp-4], ax
	mov	di, word [bp-4]
	mov	si, word [bp-2]
	mov	cx, 12
	rep
	movsw
	; >>>>> Line:	17
	; >>>>> TCBarray[currentListSize].ID = currentListSize; 
	mov	ax, word [L_linkedList_3]
	mov	cx, 36
	imul	cx
	add	ax, TCBarray
	mov	si, ax
	add	si, 34
	mov	ax, word [L_linkedList_3]
	mov	word [si], ax
	; >>>>> Line:	18
	; >>>>> currentListSize++; 
	inc	word [L_linkedList_3]
	; >>>>> Line:	19
	; >>>>> return &(TCBarray[currentListSize-1]); 
	mov	ax, word [L_linkedList_3]
	dec	ax
	mov	cx, 36
	imul	cx
	add	ax, TCBarray
L_linkedList_6:
	mov	sp, bp
	pop	bp
	ret
L_linkedList_4:
	push	bp
	mov	bp, sp
	sub	sp, 4
	jmp	L_linkedList_5
	ALIGN	2
insertTCBIntoRdyList:
	; >>>>> Line:	23
	; >>>>> { 
	jmp	L_linkedList_8
L_linkedList_9:
	; >>>>> Line:	26
	; >>>>> if (YKRdyList == 0) 
	mov	ax, word [L_linkedList_1]
	test	ax, ax
	jne	L_linkedList_10
	; >>>>> Line:	28
	; >>>>> YKRdyList = tcb; 
	mov	ax, word [bp+4]
	mov	word [L_linkedList_1], ax
	; >>>>> Line:	29
	; >>>>> tcb->next = 0; 
	mov	si, word [bp+4]
	add	si, 30
	mov	word [si], 0
	; >>>>> Line:	30
	; >>>>> tcb->prev = 0; 
	mov	si, word [bp+4]
	add	si, 32
	mov	word [si], 0
	jmp	L_linkedList_11
L_linkedList_10:
	; >>>>> Line:	34
	; >>>>> tmp = YKRdyList; 
	mov	ax, word [L_linkedList_1]
	mov	word [bp-2], ax
	; >>>>> Line:	35
	; >>>>> while (tmp->priority < tcb->priority) 
	jmp	L_linkedList_13
L_linkedList_12:
	; >>>>> Line:	36
	; >>>>> tmp = tmp->next; 
	mov	si, word [bp-2]
	add	si, 30
	mov	ax, word [si]
	mov	word [bp-2], ax
L_linkedList_13:
	mov	si, word [bp-2]
	add	si, 26
	mov	di, word [bp+4]
	add	di, 26
	mov	ax, word [di]
	cmp	ax, word [si]
	ja	L_linkedList_12
L_linkedList_14:
	; >>>>> Line:	37
	; >>>>> if (tmp->prev == 0) 
	mov	si, word [bp-2]
	add	si, 32
	mov	ax, word [si]
	test	ax, ax
	jne	L_linkedList_15
	; >>>>> Line:	38
	; >>>>> YKRdyList = tcb; 
	mov	ax, word [bp+4]
	mov	word [L_linkedList_1], ax
	jmp	L_linkedList_16
L_linkedList_15:
	; >>>>> Line:	40
	; >>>>> tmp->prev->next = tmp; 
	mov	si, word [bp-2]
	add	si, 32
	mov	si, word [si]
	add	si, 30
	mov	ax, word [bp-2]
	mov	word [si], ax
L_linkedList_16:
	; >>>>> Line:	41
	; >>>>> tcb->prev = tmp->prev; 
	mov	si, word [bp-2]
	add	si, 32
	mov	di, word [bp+4]
	add	di, 32
	mov	ax, word [si]
	mov	word [di], ax
	; >>>>> Line:	42
	; >>>>> tcb->next = tmp; 
	mov	si, word [bp+4]
	add	si, 30
	mov	ax, word [bp-2]
	mov	word [si], ax
	; >>>>> Line:	43
	; >>>>> tmp->prev = tmp; 
	mov	si, word [bp-2]
	add	si, 32
	mov	ax, word [bp-2]
	mov	word [si], ax
L_linkedList_11:
	mov	sp, bp
	pop	bp
	ret
L_linkedList_8:
	push	bp
	mov	bp, sp
	push	cx
	jmp	L_linkedList_9
	ALIGN	2
removeFirstTCBFromRdyList:
	; >>>>> Line:	48
	; >>>>> { 
	jmp	L_linkedList_18
L_linkedList_19:
	; >>>>> Line:	50
	; >>>>> tmp = YKRdyList; 
	mov	ax, word [L_linkedList_1]
	mov	word [bp-2], ax
	; >>>>> Line:	51
	; >>>>> YKRdyList = tmp->next; 
	mov	si, word [bp-2]
	add	si, 30
	mov	ax, word [si]
	mov	word [L_linkedList_1], ax
	; >>>>> Line:	52
	; >>>>> tmp->next->prev = 0; 
	mov	si, word [bp-2]
	add	si, 30
	mov	si, word [si]
	add	si, 32
	mov	word [si], 0
	; >>>>> Line:	53
	; >>>>> tmp->next = YKSuspList; 
	mov	si, word [bp-2]
	add	si, 30
	mov	ax, word [L_linkedList_2]
	mov	word [si], ax
	; >>>>> Line:	54
	; >>>>> YKSuspList = tmp; 
	mov	ax, word [bp-2]
	mov	word [L_linkedList_2], ax
	; >>>>> Line:	55
	; >>>>> tmp->prev = 0; 
	mov	si, word [bp-2]
	add	si, 32
	mov	word [si], 0
	; >>>>> Line:	56
	; >>>>> if (tmp->next != 0) 
	mov	si, word [bp-2]
	add	si, 30
	mov	ax, word [si]
	test	ax, ax
	je	L_linkedList_20
	; >>>>> Line:	57
	; >>>>> tmp->next->prev = tmp; 
	mov	si, word [bp-2]
	add	si, 30
	mov	si, word [si]
	add	si, 32
	mov	ax, word [bp-2]
	mov	word [si], ax
L_linkedList_20:
	mov	sp, bp
	pop	bp
	ret
L_linkedList_18:
	push	bp
	mov	bp, sp
	push	cx
	jmp	L_linkedList_19
	ALIGN	2
moveTCBToRdyList:
	; >>>>> Line:	64
	; >>>>> { 
	jmp	L_linkedList_22
L_linkedList_23:
	; >>>>> Line:	67
	; >>>>> if (tmp->prev == 0) 
	mov	si, word [bp+4]
	add	si, 32
	mov	ax, word [si]
	test	ax, ax
	jne	L_linkedList_24
	; >>>>> Line:	68
	; >>>>> YKSuspList = tmp->next; 
	mov	si, word [bp+4]
	add	si, 30
	mov	ax, word [si]
	mov	word [L_linkedList_2], ax
	jmp	L_linkedList_25
L_linkedList_24:
	; >>>>> Line:	70
	; >>>>> tmp->prev->next = tmp->next; 
	mov	si, word [bp+4]
	add	si, 30
	mov	di, word [bp+4]
	add	di, 32
	mov	di, word [di]
	add	di, 30
	mov	ax, word [si]
	mov	word [di], ax
L_linkedList_25:
	; >>>>> Line:	71
	; >>>>> if (tmp->next != 0) 
	mov	si, word [bp+4]
	add	si, 30
	mov	ax, word [si]
	test	ax, ax
	je	L_linkedList_26
	; >>>>> Line:	72
	; >>>>>  
	mov	si, word [bp+4]
	add	si, 32
	mov	di, word [bp+4]
	add	di, 30
	mov	di, word [di]
	add	di, 32
	mov	ax, word [si]
	mov	word [di], ax
L_linkedList_26:
	; >>>>> Line:	74
	; >>>>> tmp2 = YKRdyList; 
	mov	ax, word [L_linkedList_1]
	mov	word [bp-2], ax
	; >>>>> Line:	76
	; >>>>> while (tmp2->priority < tmp->priority) 
	jmp	L_linkedList_28
L_linkedList_27:
	; >>>>> Line:	77
	; >>>>> tmp2 = tmp2->next; 
	mov	si, word [bp-2]
	add	si, 30
	mov	ax, word [si]
	mov	word [bp-2], ax
L_linkedList_28:
	mov	si, word [bp-2]
	add	si, 26
	mov	di, word [bp+4]
	add	di, 26
	mov	ax, word [di]
	cmp	ax, word [si]
	ja	L_linkedList_27
L_linkedList_29:
	; >>>>> Line:	78
	; >>>>> if (tmp2->prev == 0) 
	mov	si, word [bp-2]
	add	si, 32
	mov	ax, word [si]
	test	ax, ax
	jne	L_linkedList_30
	; >>>>> Line:	79
	; >>>>> YKRdyList = tmp; 
	mov	ax, word [bp+4]
	mov	word [L_linkedList_1], ax
	jmp	L_linkedList_31
L_linkedList_30:
	; >>>>> Line:	81
	; >>>>> tmp2->prev->next = tmp; 
	mov	si, word [bp-2]
	add	si, 32
	mov	si, word [si]
	add	si, 30
	mov	ax, word [bp+4]
	mov	word [si], ax
L_linkedList_31:
	; >>>>> Line:	82
	; >>>>> tmp->prev = tmp2->prev; 
	mov	si, word [bp-2]
	add	si, 32
	mov	di, word [bp+4]
	add	di, 32
	mov	ax, word [si]
	mov	word [di], ax
	; >>>>> Line:	83
	; >>>>> tmp->next = tmp2; 
	mov	si, word [bp+4]
	add	si, 30
	mov	ax, word [bp-2]
	mov	word [si], ax
	; >>>>> Line:	84
	; >>>>> tmp2->prev = tmp; 
	mov	si, word [bp-2]
	add	si, 32
	mov	ax, word [bp+4]
	mov	word [si], ax
	mov	sp, bp
	pop	bp
	ret
L_linkedList_22:
	push	bp
	mov	bp, sp
	push	cx
	jmp	L_linkedList_23
L_linkedList_45:
	DB	0xA,0xA,0
L_linkedList_44:
	DB	0xA,"  IF: ",0
L_linkedList_43:
	DB	0xA,"  ds: ",0
L_linkedList_42:
	DB	0xA,"  es: ",0
L_linkedList_41:
	DB	0xA,"  bp: ",0
L_linkedList_40:
	DB	0xA,"  di: ",0
L_linkedList_39:
	DB	0xA,"  si: ",0
L_linkedList_38:
	DB	0xA,"  dx: ",0
L_linkedList_37:
	DB	0xA,"  cx: ",0
L_linkedList_36:
	DB	0xA,"  bx: ",0
L_linkedList_35:
	DB	0xA,"  ax: ",0
L_linkedList_34:
	DB	0xA,"  ip: ",0
L_linkedList_33:
	DB	0xA,"  sp: ",0
	ALIGN	2
printContext:
	; >>>>> Line:	90
	; >>>>> { 
	jmp	L_linkedList_46
L_linkedList_47:
	; >>>>> Line:	91
	; >>>>> printString("\n  sp: "); 
	mov	ax, L_linkedList_33
	push	ax
	call	printString
	add	sp, 2
	; >>>>> Line:	92
	; >>>>> printInt(c.sp); 
	push	word [bp+4]
	call	printInt
	add	sp, 2
	; >>>>> Line:	93
	; >>>>> printString("\n  ip: "); 
	mov	ax, L_linkedList_34
	push	ax
	call	printString
	add	sp, 2
	; >>>>> Line:	94
	; >>>>> printInt(c.ip); 
	push	word [bp+6]
	call	printInt
	add	sp, 2
	; >>>>> Line:	108
	; >>>>> printString("\n  ax: "); 
	mov	ax, L_linkedList_35
	push	ax
	call	printString
	add	sp, 2
	; >>>>> Line:	109
	; >>>>> printInt(c.ax); 
	push	word [bp+8]
	call	printInt
	add	sp, 2
	; >>>>> Line:	110
	; >>>>> printString("\n  bx: "); 
	mov	ax, L_linkedList_36
	push	ax
	call	printString
	add	sp, 2
	; >>>>> Line:	111
	; >>>>> printInt(c.bx); 
	push	word [bp+10]
	call	printInt
	add	sp, 2
	; >>>>> Line:	112
	; >>>>> pri 
	mov	ax, L_linkedList_37
	push	ax
	call	printString
	add	sp, 2
	; >>>>> Line:	113
	; >>>>> printInt(c.cx); 
	push	word [bp+12]
	call	printInt
	add	sp, 2
	; >>>>> Line:	114
	; >>>>> printString("\n  dx: "); 
	mov	ax, L_linkedList_38
	push	ax
	call	printString
	add	sp, 2
	; >>>>> Line:	115
	; >>>>> printInt(c.dx); 
	push	word [bp+14]
	call	printInt
	add	sp, 2
	; >>>>> Line:	116
	; >>>>> printString("\n  si: "); 
	mov	ax, L_linkedList_39
	push	ax
	call	printString
	add	sp, 2
	; >>>>> Line:	117
	; >>>>> printInt(c.si); 
	push	word [bp+16]
	call	printInt
	add	sp, 2
	; >>>>> Line:	118
	; >>>>> printString("\n  di: "); 
	mov	ax, L_linkedList_40
	push	ax
	call	printString
	add	sp, 2
	; >>>>> Line:	119
	; >>>>> printInt(c.di); 
	push	word [bp+18]
	call	printInt
	add	sp, 2
	; >>>>> Line:	120
	; >>>>> printString("\n  bp: "); 
	mov	ax, L_linkedList_41
	push	ax
	call	printString
	add	sp, 2
	; >>>>> Line:	121
	; >>>>> printInt(c.bp); 
	push	word [bp+20]
	call	printInt
	add	sp, 2
	; >>>>> Line:	122
	; >>>>> printString("\n  es: "); 
	mov	ax, L_linkedList_42
	push	ax
	call	printString
	add	sp, 2
	; >>>>> Line:	123
	; >>>>> printInt(c.es); 
	push	word [bp+22]
	call	printInt
	add	sp, 2
	; >>>>> Line:	124
	; >>>>> printString("\n  ds: "); 
	mov	ax, L_linkedList_43
	push	ax
	call	printString
	add	sp, 2
	; >>>>> Line:	125
	; >>>>> printInt(c.ds); 
	push	word [bp+24]
	call	printInt
	add	sp, 2
	; >>>>> Line:	126
	; >>>>> printString("\n  IF: "); 
	mov	ax, L_linkedList_44
	push	ax
	call	printString
	add	sp, 2
	; >>>>> Line:	127
	; >>>>> printInt(c.IF); 
	push	word [bp+26]
	call	printInt
	add	sp, 2
	; >>>>> Line:	128
	; >>>>> printString("\n\n"); 
	mov	ax, L_linkedList_45
	push	ax
	call	printString
	add	sp, 2
	mov	sp, bp
	pop	bp
	ret
L_linkedList_46:
	push	bp
	mov	bp, sp
	jmp	L_linkedList_47
L_linkedList_50:
	DB	0xA,"  Priority: ",0
L_linkedList_49:
	DB	"  ID: ",0
	ALIGN	2
printTCB:
	; >>>>> Line:	133
	; >>>>> { 
	jmp	L_linkedList_51
L_linkedList_52:
	; >>>>> Line:	134
	; >>>>> printString("  ID: "); 
	mov	ax, L_linkedList_49
	push	ax
	call	printString
	add	sp, 2
	; >>>>> Line:	135
	; >>>>> printInt(t->ID); 
	mov	si, word [bp+4]
	add	si, 34
	push	word [si]
	call	printInt
	add	sp, 2
	; >>>>> Line:	136
	; >>>>> printString("\n  Priority: "); 
	mov	ax, L_linkedList_50
	push	ax
	call	printString
	add	sp, 2
	; >>>>> Line:	137
	; >>>>> printInt(t->priority); 
	mov	si, word [bp+4]
	add	si, 26
	push	word [si]
	call	printInt
	add	sp, 2
	; >>>>> Line:	138
	; >>>>> pri 
	sub	sp, 24
	mov	di, sp
	mov	si, word [bp+4]
	mov	cx, 12
	rep
	movsw
	call	printContext
	add	sp, 24
	mov	sp, bp
	pop	bp
	ret
L_linkedList_51:
	push	bp
	mov	bp, sp
	jmp	L_linkedList_52
L_linkedList_54:
	DB	"TCB ",0
	ALIGN	2
printTCBs:
	; >>>>> Line:	142
	; >>>>> { 
	jmp	L_linkedList_55
L_linkedList_56:
	; >>>>> Line:	144
	; >>>>> for (i = 0; i < currentListSize; i++) 
	mov	word [bp-2], 0
	jmp	L_linkedList_58
L_linkedList_57:
	; >>>>> Line:	146
	; >>>>> printString("TCB "); 
	mov	ax, L_linkedList_54
	push	ax
	call	printString
	add	sp, 2
	; >>>>> Line:	147
	; >>>>> printInt(i); 
	push	word [bp-2]
	call	printInt
	add	sp, 2
	; >>>>> Line:	148
	; >>>>> printNewLine(); 
	call	printNewLine
	; >>>>> Line:	149
	; >>>>> printTCB(&TCBarray[i]); 
	mov	ax, word [bp-2]
	mov	cx, 36
	imul	cx
	add	ax, TCBarray
	push	ax
	call	printTCB
	add	sp, 2
L_linkedList_60:
	inc	word [bp-2]
L_linkedList_58:
	mov	ax, word [L_linkedList_3]
	cmp	ax, word [bp-2]
	ja	L_linkedList_57
L_linkedList_59:
	mov	sp, bp
	pop	bp
	ret
L_linkedList_55:
	push	bp
	mov	bp, sp
	push	cx
	jmp	L_linkedList_56
L_linkedList_63:
	DB	"Suspended list: ",0xA,0
L_linkedList_62:
	DB	"Ready list: ",0xA,0
	ALIGN	2
printLists:
	; >>>>> Line:	153
	; >>>>> { 
	jmp	L_linkedList_64
L_linkedList_65:
	; >>>>> Line:	156
	; >>>>> printString("Ready list: \n"); 
	mov	ax, word [L_linkedList_1]
	mov	word [bp-2], ax
	; >>>>> Line:	156
	; >>>>> printString("Ready list: \n"); 
	mov	ax, L_linkedList_62
	push	ax
	call	printString
	add	sp, 2
	; >>>>> Line:	157
	; >>>>> while (tmp != 0) 
	jmp	L_linkedList_67
L_linkedList_66:
	; >>>>> Line:	159
	; >>>>> printTCB(tmp); 
	push	word [bp-2]
	call	printTCB
	add	sp, 2
	; >>>>> Line:	160
	; >>>>> tmp = tmp->next; 
	mov	si, word [bp-2]
	add	si, 30
	mov	ax, word [si]
	mov	word [bp-2], ax
L_linkedList_67:
	mov	ax, word [bp-2]
	test	ax, ax
	jne	L_linkedList_66
L_linkedList_68:
	; >>>>> Line:	164
	; >>>>> tmp = YKSuspList; 
	mov	ax, word [L_linkedList_2]
	mov	word [bp-2], ax
	; >>>>> Line:	165
	; >>>>> printString("Suspended list: \n"); 
	mov	ax, L_linkedList_63
	push	ax
	call	printString
	add	sp, 2
	; >>>>> Line:	166
	; >>>>> while (tmp != 0) 
	jmp	L_linkedList_70
L_linkedList_69:
	; >>>>> Line:	168
	; >>>>> printTCB(tmp); 
	push	word [bp-2]
	call	printTCB
	add	sp, 2
	; >>>>> Line:	169
	; >>>>> tmp = tmp->next; 
	mov	si, word [bp-2]
	add	si, 30
	mov	ax, word [si]
	mov	word [bp-2], ax
L_linkedList_70:
	mov	ax, word [bp-2]
	test	ax, ax
	jne	L_linkedList_69
L_linkedList_71:
	mov	sp, bp
	pop	bp
	ret
L_linkedList_64:
	push	bp
	mov	bp, sp
	push	cx
	jmp	L_linkedList_65
	ALIGN	2
L_linkedList_1:
	TIMES	2 db 0
L_linkedList_2:
	TIMES	2 db 0
TCBarray:
	TIMES	216 db 0
runningTask:
	TIMES	2 db 0
IF:
	TIMES	2 db 0
