; Generated by c86 (BYU-NASM) 5.1 (beta) from interruptHandlers.i
	CPU	8086
	ALIGN	2
	jmp	main	; Jump to program start
	ALIGN	2
L_interruptHandlers_2:
	DW	0
	ALIGN	2
resetInterruptHandler:
	; >>>>> Line:	8
	; >>>>> { 
	jmp	L_interruptHandlers_3
L_interruptHandlers_4:
	; >>>>> Line:	9
	; >>>>> exit(0); 
	xor	al, al
	push	ax
	call	exit
	add	sp, 2
	mov	sp, bp
	pop	bp
	ret
L_interruptHandlers_3:
	push	bp
	mov	bp, sp
	jmp	L_interruptHandlers_4
L_interruptHandlers_6:
	DB	"TICK ",0
	ALIGN	2
tickInterruptHandler:
	; >>>>> Line:	13
	; >>>>> { 
	jmp	L_interruptHandlers_7
L_interruptHandlers_8:
	; >>>>> Line:	14
	; >>>>> tickCount++; 
	inc	word [L_interruptHandlers_2]
	; >>>>> Line:	15
	; >>>>> printNewLine(); 
	call	printNewLine
	; >>>>> Line:	16
	; >>>>> printString("TICK "); 
	mov	ax, L_interruptHandlers_6
	push	ax
	call	printString
	add	sp, 2
	; >>>>> Line:	17
	; >>>>> printInt(tickCount); 
	push	word [L_interruptHandlers_2]
	call	printInt
	add	sp, 2
	; >>>>> Line:	18
	; >>>>> printNewLine(); 
	call	printNewLine
	; >>>>> Line:	20
	; >>>>> YKTickHandler(); 
	call	YKTickHandler
	mov	sp, bp
	pop	bp
	ret
L_interruptHandlers_7:
	push	bp
	mov	bp, sp
	jmp	L_interruptHandlers_8
L_interruptHandlers_13:
	DB	") IGNORED",0
L_interruptHandlers_12:
	DB	"KEYPRESS (",0
L_interruptHandlers_11:
	DB	"DELAY COMPLETE",0
L_interruptHandlers_10:
	DB	"DELAY KEY PRESSED",0
	ALIGN	2
keyboardInterruptHandler:
	; >>>>> Line:	24
	; >>>>> { 
	jmp	L_interruptHandlers_14
L_interruptHandlers_15:
	; >>>>> Line:	26
	; >>>>> printNewLine(); 
	call	printNewLine
	; >>>>> Line:	27
	; >>>>> if (KeyBuffer == 'd') 
	cmp	word [KeyBuffer], 100
	jne	L_interruptHandlers_16
	; >>>>> Line:	29
	; >>>>> printString("DEL 
	mov	ax, L_interruptHandlers_10
	push	ax
	call	printString
	add	sp, 2
	; >>>>> Line:	30
	; >>>>> count = 0; 
	mov	word [bp-2], 0
	; >>>>> Line:	31
	; >>>>> while (count < 5000) 
	jmp	L_interruptHandlers_18
L_interruptHandlers_17:
	; >>>>> Line:	33
	; >>>>> count++; 
	inc	word [bp-2]
L_interruptHandlers_18:
	cmp	word [bp-2], 5000
	jl	L_interruptHandlers_17
L_interruptHandlers_19:
	; >>>>> Line:	35
	; >>>>> printNewLine(); 
	call	printNewLine
	; >>>>> Line:	36
	; >>>>> printString("DELAY COMPLETE"); 
	mov	ax, L_interruptHandlers_11
	push	ax
	call	printString
	add	sp, 2
	; >>>>> Line:	37
	; >>>>> printNewLine(); 
	call	printNewLine
	jmp	L_interruptHandlers_20
L_interruptHandlers_16:
	; >>>>> Line:	41
	; >>>>> printString("KEYPRESS ("); 
	mov	ax, L_interruptHandlers_12
	push	ax
	call	printString
	add	sp, 2
	; >>>>> Line:	42
	; >>>>> printChar(KeyBuffer); 
	push	word [KeyBuffer]
	call	printChar
	add	sp, 2
	; >>>>> Line:	43
	; >>>>> printString(") IGNORED"); 
	mov	ax, L_interruptHandlers_13
	push	ax
	call	printString
	add	sp, 2
	; >>>>> Line:	44
	; >>>>> printNewLine(); 
	call	printNewLine
L_interruptHandlers_20:
	mov	sp, bp
	pop	bp
	ret
L_interruptHandlers_14:
	push	bp
	mov	bp, sp
	push	cx
	jmp	L_interruptHandlers_15
	ALIGN	2
L_interruptHandlers_1:
	TIMES	512 db 0
