; Generated by c86 (BYU-NASM) 5.1 (beta) from yakc.i
	CPU	8086
	ALIGN	2
	jmp	main	; Jump to program start
	ALIGN	2
YKIdleCount:
	DW	0
L_yakc_2:
	DW	0
ISRCallDepth:
	DW	0
lastRunTask:
	DW	0
YKCtxSwCount:
	DW	0
YKTickNum:
	DW	0
firstTime:
	DW	1
initContext:
	DW	0,0,0,0,0
	DW	0,0,0,0,0
	DW	0,0,512
	ALIGN	2
YKInitialize:
	; >>>>> Line:	32
	; >>>>> { 
	jmp	L_yakc_3
L_yakc_4:
	; >>>>> Line:	36
	; >>>>> YKNewTask(YKIdleTask, (void *) &IdleStk[256], 100); 
	mov	al, 100
	push	ax
	mov	ax, (L_yakc_1+512)
	push	ax
	mov	ax, YKIdleTask
	push	ax
	call	YKNewTask
	add	sp, 6
	; >>>>> Line:	38
	; >>>>> lastRunTask = YKRdyList; 
	mov	ax, word [YKRdyList]
	mov	word [lastRunTask], ax
	mov	sp, bp
	pop	bp
	ret
L_yakc_3:
	push	bp
	mov	bp, sp
	jmp	L_yakc_4
	ALIGN	2
YKIdleTask:
	; >>>>> Line:	42
	; >>>>> { 
	jmp	L_yakc_6
L_yakc_7:
	; >>>>> Line:	43
	; >>>>> while(1) 
	jmp	L_yakc_9
L_yakc_8:
	; >>>>> Line:	46
	; >>>>> tmp = YKIdleCount + 1; 
	mov	ax, word [YKIdleCount]
	inc	ax
	mov	word [bp-2], ax
	; >>>>> Line:	47
	; >>>>> YKIdleCount = tmp; 
	mov	ax, word [bp-2]
	mov	word [YKIdleCount], ax
L_yakc_9:
	jmp	L_yakc_8
L_yakc_10:
	mov	sp, bp
	pop	bp
	ret
L_yakc_6:
	push	bp
	mov	bp, sp
	push	cx
	jmp	L_yakc_7
	ALIGN	2
YKNewTask:
	; >>>>> Line:	54
	; >>>>> { 
	jmp	L_yakc_12
L_yakc_13:
	; >>>>> Line:	62
	; >>>>> newTCB = createTCB(taskStack, priority, initContext); 
	sub	sp, 26
	mov	di, sp
	mov	si, initContext
	mov	cx, 13
	rep
	movsw
	mov	al, byte [bp+8]
	xor	ah, ah
	push	ax
	push	word [bp+6]
	call	createTCB
	add	sp, 30
	mov	word [bp-2], ax
	; >>>>> Line:	64
	; >>>>> newTCB->con 
	mov	si, word [bp-2]
	mov	ax, word [bp+6]
	mov	word [si], ax
	; >>>>> Line:	65
	; >>>>> newTCB->context.ip = (int)task; 
	mov	si, word [bp-2]
	add	si, 2
	mov	ax, word [bp+4]
	mov	word [si], ax
	; >>>>> Line:	66
	; >>>>> newTCB->context.bp = (int)taskStack; 
	mov	si, word [bp-2]
	add	si, 16
	mov	ax, word [bp+6]
	mov	word [si], ax
	; >>>>> Line:	67
	; >>>>> insertTCBIntoRdyList(newTCB); 
	push	word [bp-2]
	call	insertTCBIntoRdyList
	add	sp, 2
	; >>>>> Line:	71
	; >>>>> if (running_flag) 
	mov	ax, word [L_yakc_2]
	test	ax, ax
	je	L_yakc_14
	; >>>>> Line:	73
	; >>>>> YKScheduler(); 
	call	YKScheduler
L_yakc_14:
	mov	sp, bp
	pop	bp
	ret
L_yakc_12:
	push	bp
	mov	bp, sp
	push	cx
	jmp	L_yakc_13
	ALIGN	2
YKRun:
	; >>>>> Line:	78
	; >>>>> { 
	jmp	L_yakc_16
L_yakc_17:
	; >>>>> Line:	81
	; >>>>> running_flag = 1; 
	mov	word [L_yakc_2], 1
	; >>>>> Line:	84
	; >>>>> YKScheduler(); 
	call	YKScheduler
	mov	sp, bp
	pop	bp
	ret
L_yakc_16:
	push	bp
	mov	bp, sp
	jmp	L_yakc_17
	ALIGN	2
YKDelayTask:
	; >>>>> Line:	88
	; >>>>> { 
	jmp	L_yakc_19
L_yakc_20:
	; >>>>> Line:	93
	; >>>>> if (count == 0) 
	mov	ax, word [bp+4]
	test	ax, ax
	jne	L_yakc_21
	; >>>>> Line:	94
	; >>>>> return; 
	jmp	L_yakc_22
L_yakc_21:
	; >>>>> Line:	97
	; >>>>> YKRdyList->delay = count; 
	mov	si, word [YKRdyList]
	add	si, 30
	mov	ax, word [bp+4]
	mov	word [si], ax
	; >>>>> Line:	98
	; >>>>> removeFirstTCBFromRdyList(); 
	call	removeFirstTCBFromRdyList
	; >>>>> Line:	99
	; >>>>> YKScheduler(); 
	call	YKScheduler
L_yakc_22:
	mov	sp, bp
	pop	bp
	ret
L_yakc_19:
	push	bp
	mov	bp, sp
	jmp	L_yakc_20
	ALIGN	2
YKEnterISR:
	; >>>>> Line:	103
	; >>>>> { 
	jmp	L_yakc_24
L_yakc_25:
	; >>>>> Line:	104
	; >>>>> ISRCallDepth++; 
	inc	word [ISRCallDepth]
	mov	sp, bp
	pop	bp
	ret
L_yakc_24:
	push	bp
	mov	bp, sp
	jmp	L_yakc_25
	ALIGN	2
YKExitISR:
	; >>>>> Line:	108
	; >>>>> { 
	jmp	L_yakc_27
L_yakc_28:
	; >>>>> Line:	109
	; >>>>> ISRCallDepth--; 
	dec	word [ISRCallDepth]
	; >>>>> Line:	110
	; >>>>> if (ISRCallDepth == 0) 
	mov	ax, word [ISRCallDepth]
	test	ax, ax
	jne	L_yakc_29
	; >>>>> Line:	111
	; >>>>> YKScheduler(); 
	call	YKScheduler
L_yakc_29:
	mov	sp, bp
	pop	bp
	ret
L_yakc_27:
	push	bp
	mov	bp, sp
	jmp	L_yakc_28
	ALIGN	2
YKScheduler:
	; >>>>> Line:	115
	; >>>>> { 
	jmp	L_yakc_31
L_yakc_32:
	; >>>>> Line:	119
	; >>>>> if (lastRunTask != YKRdyList || firstTime) 
	mov	ax, word [YKRdyList]
	cmp	ax, word [lastRunTask]
	jne	L_yakc_34
	mov	ax, word [firstTime]
	test	ax, ax
	je	L_yakc_33
L_yakc_34:
	; >>>>> Line:	121
	; >>>>> firstTime = 0; 
	mov	word [firstTime], 0
	; >>>>> Line:	124
	; >>>>> YKCtxSwCount++; 
	inc	word [YKCtxSwCount]
	; >>>>> Line:	125
	; >>>>> YKDispatcher(); 
	call	YKDispatcher
L_yakc_33:
	mov	sp, bp
	pop	bp
	ret
L_yakc_31:
	push	bp
	mov	bp, sp
	jmp	L_yakc_32
	ALIGN	2
YKTickHandler:
	; >>>>> Line:	131
	; >>>>> { 
	jmp	L_yakc_36
L_yakc_37:
	; >>>>> Line:	140
	; >>>>> tmp = YKSuspList; 
	mov	ax, word [YKSuspList]
	mov	word [bp-2], ax
	; >>>>> Line:	141
	; >>>>> while(tmp != 0) 
	jmp	L_yakc_39
L_yakc_38:
	; >>>>> Line:	143
	; >>>>> if (tmp->delay > 0) 
	mov	si, word [bp-2]
	add	si, 30
	cmp	word [si], 0
	jle	L_yakc_41
	; >>>>> Line:	145
	; >>>>> tmp->delay--; 
	mov	si, word [bp-2]
	add	si, 30
	dec	word [si]
	; >>>>> Line:	146
	; >>>>> if (tmp->delay == 0) 
	mov	si, word [bp-2]
	add	si, 30
	mov	ax, word [si]
	test	ax, ax
	jne	L_yakc_42
	; >>>>> Line:	148
	; >>>>> tmp2 = tmp; 
	mov	ax, word [bp-2]
	mov	word [bp-4], ax
	; >>>>> Line:	149
	; >>>>> tmp = tmp->next; 
	mov	si, word [bp-2]
	add	si, 32
	mov	ax, word [si]
	mov	word [bp-2], ax
	; >>>>> Line:	150
	; >>>>> moveTCBToRdyList(tmp2); 
	push	word [bp-4]
	call	moveTCBToRdyList
	add	sp, 2
	jmp	L_yakc_43
L_yakc_42:
	; >>>>> Line:	153
	; >>>>> tmp = tmp->next; 
	mov	si, word [bp-2]
	add	si, 32
	mov	ax, word [si]
	mov	word [bp-2], ax
L_yakc_43:
	jmp	L_yakc_44
L_yakc_41:
	; >>>>> Line:	156
	; >>>>> tmp = tmp->next; 
	mov	si, word [bp-2]
	add	si, 32
	mov	ax, word [si]
	mov	word [bp-2], ax
L_yakc_44:
L_yakc_39:
	mov	ax, word [bp-2]
	test	ax, ax
	jne	L_yakc_38
L_yakc_40:
	; >>>>> Line:	158
	; >>>>> YKTickNum++; 
	inc	word [YKTickNum]
	mov	sp, bp
	pop	bp
	ret
L_yakc_36:
	push	bp
	mov	bp, sp
	sub	sp, 4
	jmp	L_yakc_37
	ALIGN	2
L_yakc_1:
	TIMES	512 db 0
